name: "[SITE_NAME]"
project: "[SITE_PROJECT]"
url: "[URL]"
autoprefixer:
  - "last 5 versions"
  - "ie 9"
  - "ie 10"
  - "ie 11"
  - "ios >= 7"
  - "android >= 4.4"
  - "opera 12"
path:
  dist: "[PATH_TO_THEME]"
  src: "[PATH_TO_SOURCE]"
pathfolder:
  source: /source
  dist:
    css: /css
    images: /images
    fonts: /fonts
    libraries: /libraries
    js: /js
assets:
  colors:
    default:   "[COLORZ_DEFAULT]"
    primary:   "[COLORZ_PRIMARY]"
    secondary: "[COLORZ_SECONDARY]"
